### ISSUE TITLE
generator

### ISSUE THREAD

**Issue by long191910** [monosans/nitro-generator-checker#258]
how long does it take to gen a nitro?

**Comment by monosans** [comment]
It's random

**Comment by stefnotch** [comment]
Short answer: *Forever.* You'll never get a code with this, or with any other Discord Nitro Generator.

Long answer:
It's an easy bit of statistics: A random potential nitro code gets generated here.

https://github.com/monosans/nitro-generator-checker/blob/38728ef7b0e3f23edb61908f1ab3c8b57f3946ec/nitro_generator_checker/nitro_generator.py#L22

So 16 characters, where each character can either be a lowercase letter (26), an uppercase letter (26) or a digit (10).
That gives us $(26+26+10)^{16}$ possible combinations.

Now how many of those are valid? We have no idea, but we can easily find an upper bound. For example, assuming Discord has a nitro code for every human on the planet, we only have 7 billion valid codes.

So what are the odds of finding a valid code? Plugging the number into Wolfy Alphy, we get
https://www.wolframalpha.com/input?i=7*10%5E9%2F%2826%2B26%2B10%29%5E16

Now how long does it take to get a valid code? Well the odds of finding at least one valid code after N attempts is $P = 1 - (1- p)^N$

So with a million tries, your odds are still effectively zero. You have so much better odds if you chose to mine some bitcoins and then played the lottery. Feel free to try plugging in increasingly large and absurd numbers.
https://www.wolframalpha.com/input?i=1+-+%281+-+%287*10%5E9%2F%2826%2B26%2B10%29%5E16%29%29%5E1000000
